spring:
  application:
    name: DOSW-Library
  profiles:
    active: mongo
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/dosw_library}

app:
  security:
    jwt:
      secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
      ttl-millis: 3600000

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore/dosw-library.p12
    key-store-password: changeit
    key-store-type: PKCS12
